<?php

/*
 * @file
 * Custom webform calculations and validation.
 * Outputs messages to the end user using drupal_set_message.
 */

/*
 * Implements hook_form_alter().
 */
function calcform_form_alter(&$form, $form_state, $form_id) {
  dsm($form_id);
  if ($form_id == 'webform_client_form_3') {
    $form['#validate'][] = 'area_calcform_validate';
  }
}

/*
 * Custom webform validation and calculations.
 * Applies to webform 1.
 */
function area_calcform_validate($form, &$form_state) {
  
  $answer = $form_state['input']['submitted']['question1'];

  form_set_value($form['submitted']['answer'], $answer, $form_state);

  dsm('Answer is ' . $answer); // DEVEL Code.

  if ($answer > 100) {
    drupal_set_message(t('Area is ' . $area . '. Validation window is green.'), 'status');
  }
  else {
    drupal_set_message(t('Area too small, validation window is red'), 'error');
  }
  
  return $form;
}